In [1]:
import numpy
import py_qip

## Simple Timings

In [2]:
b = py_qip.Circuit(qubits=10)
b.run_circuit()

array([1.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j])

In [3]:
b.apply_unitary([0], numpy.array([[0,1],[1,0]], dtype=numpy.complex128))

%timeit b.run_circuit()

49.5 µs ± 370 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
b.apply_unitary([9,0], numpy.array([[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]], dtype=numpy.complex128))

%timeit b.run_circuit()

95.6 µs ± 2.61 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Initial States

In [5]:
b = py_qip.Circuit(qubits=2)
b.apply_unitary([0], numpy.array([[0,1],[1,0]], dtype=numpy.complex128))

In [6]:
# Apply X to |0,0>
b.run_circuit()

array([0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j])

In [7]:
# Apply X to |1,1>
b.run_circuit(initial_state=[(0, True), (1, True)])

array([0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])